version: '3.1'

services:
    db:
        image: postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: worblehat-pw

    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - "8081:8080"
        depends_on:
            - db

    worblehat:
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            DATABASE_HOST: db
            DATABASE_PORT: 5432
        ports:
            - 8080:8080
        depends_on:
            - db
