# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Maven Install & Unit Tests
      run: ./mvnw install
    - name: Testcontainers E2E Tests
      run: ./mvnw -P runITs verify
    - uses: actions/upload-artifact@v2
      with:
        name: Video
        path: worblehat-acceptancetests/target/*.flv
    - uses: actions/upload-artifact@v2
      with:
        name: Acceptance Test Report
        path: worblehat-acceptancetests/target/cucumber